### ISSUE TITLE
New version (1.0.5??) doesn't work

### ISSUE THREAD

**Issue by bushrang3r** [SubhamTyagi/AppLock#23]
There's no version number listed anywhere in the new version but I guess it's 1.0.5.

The app starts and I can navigate around inside the settings, but trying to use it to lock apps doesn't work. 
It now runs in the background, but there should probably be the option to turn that off.

Galaxy NOTE 4
Resurrection Remix Tom
Android 9

**Comment by Kudalufi** [comment]
Same for Android 6.0.2 and Samsung Galaxy S5

Applock no longer automatically takes you to usage tracking to enable it.  Probably because the option to switch between usage tracking and accessibility has been removed.  However even if usage tracking is manually allowed it still doesn't work.

The app
