### ISSUE TITLE
copycat on google play?

### ISSUE THREAD

**Issue by Poussinou** [SubhamTyagi/AppLock#43]
Hi @SubhamTyagi ,

I found this app on Google Play : https://play.google.com/store/apps/details?id=io.github.subhamtyagi.privacyapplock

Is it your google play account? It looks like it's not the case, but I want to be sure.

**Comment by SubhamTyagi** [comment]
Thanks for your attention.

i doesn't have any play store account. 
it is a copycat app

**Comment by SubhamTyagi** [comment]
another one

https://play.google.com/store/apps/details?id=io.urbonsolution.deepak.privacyapplock

**Comment by Poussinou** [comment]
Thanks for the report

**Comment by kurahaupo** [comment]
@poussinou
A DCMA takedown would in this case require making a false statutory declaration, which would be a really bad idea as perjury can result in jail time.
It's not infringing when the Apache licence expressly permits anyone to make commercial use of this project.
And that's assuming they forked this and didn't build from scratch.

**Comment by Poussinou** [comment]
Conditions to reuse source code under Apache V2 license are:
*  License and copyright notice;
*  State changes. (according to the [license in the repo](https://github.com/SubhamTyagi/AppLock/blob/master/LICENSE))

Commercial use, personal use, modification, distribution are obviously permitted (and I support it), AS LONS AS you respect the license. That's not the case here.

According to the last update date, they probably based their code on the @SubhamTyagi 's AppLock version, so he's totally allowed to fill a DMCA takedown request, because he owns at least a part of the source code.

The UI is obviously the same, so no, they didn't build it from scratch, and yes they did some changes because they added ads and/or changed the package id (but they didn't stated them).

Conclusion: DMCA takedown request is permitted, allowed and recommended here.

**Comment by SubhamTyagi** [comment]
As soon as i get time i will fill the DMCA takedown request.

**Comment by kurahaupo** [comment]
Of course you are quite correct about the compliance requirements for modified versions under the Apache licence.

However a formal DCMA take-down is rather over-the-top, when Google already provides a way to "flag as inappropriate", which includes [impersonation and intellectual property](https://play.google.com/about/ip-impersonation/ip/#!?zippy_activeEl=unauthorized-copyright#unauthorized-copyright).

Anyone other than Poussinou still has to be careful to avoid making a perjurous declaration, as a valid DCMA request includes an assertion that the requester is the copyright owner or the copyright owner's appointed enforcement agent. Unless Poussinou gives the go-ahead, this could be problematic.

The Omnia Software app is troubling in that it appears to be a blatant attempt to monetize other people's work, without acknowledgement, and by using Poussinou's github.io path as the project ID. (Currently "Omnia Software" only has this one app published.) As part of any complaint, ask for the ID to be released so that Poussinou can use it, or at least not be impersonated.

The Deepak S Mishra app is less troubling: it's ad-free and would appear to be simply a republication of the app; in any case, engaging with the developer directly would appear to be more appropriate. Just ask nicely to have "open source" and a link back to github added to the app description.

**Comment by kurahaupo** [comment]
@SubhamTyagi
https://support.google.com/googleplay/android-developer/contact/takedown
cite "Unlawful activities"
